// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPI.Models.Migrations
{
    [DbContext(typeof(WebAPIDbContext))]
    [Migration("20230723191107_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyName = "Aspekt"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyName = "Makpetrol"
                        },
                        new
                        {
                            CompanyId = 3,
                            CompanyName = "Mcdonald's"
                        },
                        new
                        {
                            CompanyId = 4,
                            CompanyName = "Microsoft"
                        },
                        new
                        {
                            CompanyId = 5,
                            CompanyName = "Spotify"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("ContactId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CompanyId = 1,
                            ContactName = "Quincy Bell",
                            CountryId = 1
                        },
                        new
                        {
                            ContactId = 2,
                            CompanyId = 2,
                            ContactName = "Kendra Cartwright",
                            CountryId = 3
                        },
                        new
                        {
                            ContactId = 3,
                            CompanyId = 2,
                            ContactName = "Random Name",
                            CountryId = 2
                        },
                        new
                        {
                            ContactId = 4,
                            CompanyId = 4,
                            ContactName = "Andrew Smith",
                            CountryId = 3
                        },
                        new
                        {
                            ContactId = 5,
                            CompanyId = 5,
                            ContactName = "Darell Overton",
                            CountryId = 3
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Macedonia"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "Germany"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Contact", b =>
                {
                    b.HasOne("WebAPI.Models.Entities.Company", null)
                        .WithMany("Contact")
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebAPI.Models.Entities.Country", null)
                        .WithMany("Contact")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Company", b =>
                {
                    b.Navigation("Contact");
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Country", b =>
                {
                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
